# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor


class InfoCard(QtWidgets.QFrame):
    def __init__(self, icon_path, title, description):
        super().__init__()
        self.setFixedSize(200, 220)
        self.setStyleSheet("""
            QFrame {
                background: white;
                border-radius: 15px;
                border: none;
            }
            QFrame:hover {
                background: #F5F9FF;
            }
        """)
        
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(15)
        shadow.setColor(QColor(0, 0, 0, 40))
        shadow.setOffset(0, 2)
        self.setGraphicsEffect(shadow)
        
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(15, 15, 15, 15)
        layout.setSpacing(10)
        
        icon_label = QtWidgets.QLabel()
        icon_label.setFixedSize(60, 60)
        icon_pixmap = QtGui.QPixmap(icon_path)
        if not icon_pixmap.isNull():
            icon_label.setPixmap(icon_pixmap.scaled(60, 60, Qt.KeepAspectRatio, Qt.SmoothTransformation))
        icon_label.setAlignment(Qt.AlignCenter)
        
        title_label = QtWidgets.QLabel(title)
        title_label.setStyleSheet("""
            QLabel {
                color: #1E88E5;
                font-size: 18px;
                font-weight: bold;
                font-family: 'Segoe UI';
            }
        """)
        title_label.setAlignment(Qt.AlignCenter)
        title_label.setWordWrap(True)
        
        desc_label = QtWidgets.QLabel(description)
        desc_label.setStyleSheet("""
            QLabel {
                color: #666;
                font-size: 14px;
                line-height: 1.4;
            }
        """)
        desc_label.setWordWrap(True)
        desc_label.setAlignment(Qt.AlignCenter)
        
        layout.addWidget(icon_label, alignment=Qt.AlignCenter)
        layout.addWidget(title_label)
        layout.addWidget(desc_label)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setStyleSheet("""
            QMainWindow {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #E8F0FE, stop:1 #FFFFFF);
            }
        """)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)
        
        # Left panel for logo and buttons
        left_panel = QtWidgets.QFrame()
        left_panel.setFixedWidth(512)
        left_panel.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #1E88E5, stop:1 #64B5F6);
            }
        """)
        
        left_layout = QtWidgets.QVBoxLayout(left_panel)
        left_layout.setContentsMargins(40, 40, 40, 40)
        left_layout.setSpacing(25)
        
        # Logo
        self.image_label = QtWidgets.QLabel()
        self.image_label.setFixedSize(250, 250)
        
        logo_pixmap = QtGui.QPixmap("assets/Saathilogo2.png")
        if not logo_pixmap.isNull():
            self.image_label.setPixmap(logo_pixmap.scaled(
                250, 250, 
                Qt.KeepAspectRatio, 
                Qt.SmoothTransformation
            ))
        else:
            self.image_label.setStyleSheet("""
                QLabel {
                    background-color: rgba(255, 255, 255, 0.1);
                    border-radius: 125px;
                    color: white;
                    font-size: 96px;
                    font-weight: bold;
                    font-family: 'Segoe UI';
                }
            """)
            self.image_label.setText("Saathi")
            self.image_label.setAlignment(Qt.AlignCenter)
        
        # Welcome text
        welcome_text = QtWidgets.QLabel("Connect.Share.Thrive")
        welcome_text.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 36px;
                font-weight: bold;
                font-family: 'Segoe UI';
                padding: 0 20px;
                word-wrap: break-word;
            }
        """)
        welcome_text.setAlignment(Qt.AlignCenter)
        welcome_text.setWordWrap(True)
        
        # Description
        description = QtWidgets.QLabel(
            "Connect with like-minded individuals and\n"
            "build lasting friendships in a safe environment."
        )
        description.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 0.9);
                font-size: 20px;
            }
        """)
        description.setAlignment(Qt.AlignCenter)
        
        # Buttons container
        buttons_container = QtWidgets.QWidget()
        buttons_layout = QtWidgets.QVBoxLayout(buttons_container)
        buttons_layout.setSpacing(20)
        
        self.pushButton = QtWidgets.QPushButton("Log In")
        self.pushButton.setFixedSize(250, 55)
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: white;
                color: #1E88E5;
                border: none;
                border-radius: 27px;
                font-size: 20px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #F5F9FF;
            }
        """)
        
        self.pushButton_2 = QtWidgets.QPushButton("Create Account")
        self.pushButton_2.setFixedSize(250, 55)
        self.pushButton_2.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                color: white;
                border: 2px solid white;
                border-radius: 27px;
                font-size: 20px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: rgba(255, 255, 255, 0.1);
            }
        """)
        
        buttons_layout.addWidget(self.pushButton, alignment=Qt.AlignCenter)
        buttons_layout.addWidget(self.pushButton_2, alignment=Qt.AlignCenter)
        
        # Add widgets to left layout
        left_layout.addWidget(self.image_label, alignment=Qt.AlignCenter)
        left_layout.addWidget(welcome_text)
        left_layout.addWidget(description)
        left_layout.addStretch()
        left_layout.addWidget(buttons_container)
        
        # Right panel for info cards
        right_panel = QtWidgets.QFrame()
        right_panel.setStyleSheet("""
            QFrame {
                background: white;
            }
        """)
        
        right_layout = QtWidgets.QVBoxLayout(right_panel)
        right_layout.setContentsMargins(40, 40, 40, 40)
        right_layout.setSpacing(25)
        
        # Section title
        features_title = QtWidgets.QLabel("Why Choose Saathi?")
        features_title.setStyleSheet("""
            QLabel {
                color: #1E88E5;
                font-size: 32px;
                font-weight: bold;
                font-family: 'Segoe UI';
            }
        """)
        features_title.setAlignment(Qt.AlignCenter)
        
        # Cards container
        cards_container = QtWidgets.QWidget()
        cards_layout = QtWidgets.QGridLayout(cards_container)
        cards_layout.setSpacing(20)
        cards_layout.setContentsMargins(0, 0, 0, 0)
        
        # Create info cards
        cards = [
            InfoCard(
                "icons/privacy.png",
                "Safe & Secure",
                "Your safety is our priority with verified users and strict privacy."
            ),
            InfoCard(
                "icons/friends.png",
                "Smart Matching",
                "Connect with people who share your interests and values."
            ),
            InfoCard(
                "icons/chat.png",
                "Live Chat",
                "Chat freely with your friends."
            ),
            InfoCard(
                "icons/event.png",
                "Track Events",
                "Track different types of events around you."
            )
        ]
        
        # Add cards to grid layout
        for i, card in enumerate(cards):
            row = i // 2
            col = i % 2
            cards_layout.addWidget(card, row, col)
        
        right_layout.addWidget(features_title)
        right_layout.addWidget(cards_container)
        
        # Add panels to main layout
        main_layout.addWidget(left_panel)
        main_layout.addWidget(right_panel)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome to Saathi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())